### PR TITLE
Update client.lua

### PR DESCRIPTION
**Pull request by ItzMuri**

### CODE REVIEW

**Comment by xFutte** [comment]
@ItzMuri This change does what exactly?

**Comment by ItzMuri** [comment]
hahaha some saying you copied cdn code

**Comment by ItzMuri** [comment]
image

**Comment by ItzMuri** [comment]
i did copy just want remove for no more issue

**Comment by MonkeyWhisper** [comment]
> i did copy just want remove for no more issue

Nah, leave it. I don't give a fuck. 

THEY copied ps-fuel and re-release it as cdn-fuel.

**Pull request closed without merging**
